const serviceOptions = [
  { label: "Hair Cutting & Styling", value: "hair-cutting-styling" },
  { label: "Hair Coloring", value: "hair-coloring" },
  { label: "Highlights/Lowlights", value: "highlights-lowlights" },
  { label: "Balayage", value: "balayage" },
  { label: "Ombre", value: "ombre" },
  { label: "Hair Treatments", value: "hair-treatments" },
  { label: "Keratin Treatment", value: "keratin-treatment" },
  { label: "Hair Spa", value: "hair-spa" },
  { label: "Hair Smoothening", value: "hair-smoothening" },
  { label: "Hair Rebonding", value: "hair-rebonding" },
  { label: "Perming", value: "perming" },
  { label: "Hair Extensions", value: "hair-extensions" },
  { label: "Hair Weaving", value: "hair-weaving" },
  { label: "Hair Updos", value: "hair-updos" },
  { label: "Blow Dry", value: "blow-dry" },
  { label: "Hair Wash & Conditioning", value: "hair-wash-conditioning" },
  { label: "Bridal Makeup", value: "bridal-makeup" },
  { label: "Party Makeup", value: "party-makeup" },
  { label: "Engagement Makeup", value: "engagement-makeup" },
  { label: "Reception Makeup", value: "reception-makeup" },
  { label: "Day Makeup", value: "day-makeup" },
  { label: "Evening Makeup", value: "evening-makeup" },
  { label: "Character Makeup", value: "character-makeup" },
  { label: "Skin Care", value: "skin-care" },
  { label: "Facial", value: "facial" },
  { label: "Clean Up", value: "clean-up" },
  { label: "Bleach", value: "bleach" },
  { label: "Waxing", value: "waxing" },
  { label: "Threading", value: "threading" },
  { label: "Manicure", value: "manicure" },
  { label: "Pedicure", value: "pedicure" },
  { label: "Nail Art", value: "nail-art" },
  { label: "Nail Extensions", value: "nail-extensions" },
  { label: "Acne Treatment", value: "acne-treatment" },
  { label: "Anti-Aging Treatment", value: "anti-aging-treatment" },
  { label: "Men's Haircut", value: "mens-haircut" },
  { label: "Beard Trim", value: "beard-trim" },
  { label: "Shave", value: "shave" },
  { label: "Men's Facial", value: "mens-facial" },
  { label: "Hair Consultation", value: "hair-consultation" },
  { label: "Makeup Lessons", value: "makeup-lessons" },
  { label: "Hair & Scalp Analysis", value: "hair-scalp-analysis" },
  { label: "Other", value: "other" }
];
export default serviceOptions;
